### ISSUE TITLE
Unable to create policies for COPE devices 

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1007]
The select group only has BYOD and ANY as the values. COPE needs to be added to the drop-down list.

**Comment by shavidissa** [comment]
![screen shot 2017-06-16 at 2 11 12 pm](https://user-images.githubusercontent.com/22474854/27219057-e29e113a-529d-11e7-90c4-8e41accefc2d.png)

**Comment by shavidissa** [comment]
The device type the policy needs to be pushed to is updated based on the devices enrolled in the system. If only BYOD devices are there then only BYOD and NONE will show. If no devices are enrolled only NONE will show. 

But we have to show all the device type groups despite what device is already enrolled.
coz policies are created beforehand too and published to the devices at enrollment

**Comment by charithag** [comment]
BYOD and COPE groups are system groups and will created upon adding the first device with particular ownership. In order to have the COPE group you might needed to have at least one COPE device enrolled.

However above implementation will prevent adding future polices for devices which doesn't exists yet. So IMO, we can create both BYOD and COPE groups when server is starting up for the first time.

**Comment by inoshperera** [comment]
Closing the issue based on following doc JIRA,
https://wso2.org/jira/browse/DOCUMENTATION-4545

**Comment by shavidissa** [comment]
Hi Team,

Based on the discussion we had with Charitha G, Geeth and Ayyoob. I am reopening this issue again.

We need to have the ANY (currently it says NONE), BYOD, COPE , and maybe COSU (as discussed) in the drop-down as discussed today

**Comment by geethkokila** [comment]
Fixes https://github.com/wso2/carbon-device-mgt/pull/852
