### ISSUE TITLE
[Device Details] Device details page takes a long time to load

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1082]
Pre-Conditions:
- IoTS should be up and running
- A device should be registered as BYOD

Steps:
1. Go to device management page
2. Click on a device title
3. Observe the behaviour

Expected Results:-
- UI shouldn't take a long time to be loaded

Actual Results:-
- UI takes a long time to be loaded

**Comment by pubudup** [comment]
@chamaraanu : Labels: high, 3.1.0-alpha

**Comment by dunithd** [comment]
This is fixed with #https://github.com/wso2/carbon-device-mgt/pull/816

Earlier, before loading the device details page, GeoLocation service is being called to get the location history data for the device. When analytics node is down, GeoLocation service is not accessible. So there was a reconnect attempt goes on, delaying the page load.

The fix was applied to check the property in the <PRODUCT_HOME>/conf/cdm-confg.xml file before making a call to GeoLocationService. It is set to false by default so that it prevents making an unnecessary call if the analytics server has been stopped.

**Comment by pubudup** [comment]
Verified in 3.1.0-RC
