### ISSUE TITLE
Temperature data for raspberry not populated on graph

### ISSUE THREAD

**Issue by tonny1983** [wso2/product-iots#1104]
I used testAgent.sh to publish demo data to MQTT broker. 

For Raspberry agent, the output is:
>~~~~~~~~~~~~~~~~~~~~~~~~ Publishing Device-Data ~~~~~~~~~~~~~~~~~~~~~~~~~
>PUBLISHED DATA: {"event":{"metaData":{"owner":"admin","type":"raspberrypi","deviceId":"1iaxp3e5u3jvn","time":1499076724},"payloadData":{"temperature":25.00}}}
>PUBLISHED TOPIC: carbon.super/raspberrypi/1iaxp3e5u3jvn/temperature
>MQTT_LISTENER: Mon Jul  3 18:12:04 2017 Connected to MQTT Broker - xxx:1886
>MQTT_LISTENER: Connected with result code 0
>MQTT_LISTENER: Subscribing with topic carbon.super/raspberrypi/1iaxp3e5u3jvn
>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> RASPBERRY_STATS: Temp=32.0*C  Humidity=35.0%
>Temperature Data Published Succesfully

For broker server, the output is:
>[2017-07-03 18:12:02,316] [IoT-Broker]  INFO {org.dna.mqtt.moquette.messaging.spi.impl.ProtocolProcessor} -  cleaning old saved subscriptions for client 87654321
>[2017-07-03 18:12:02,354] [IoT-Broker]  INFO {org.wso2.andes.subscription.SubscriptionEngine} -  Local subscription ADDED [carbon.super/raspberrypi/1iaxp3e5u3jvn]ID=carbon:87654321:carbon.super/raspberrypi/1iaxp3e5u3jvn@NODExxx/a.b.c.d/T=1499076722352/D=false/X=true/O=/E=amq.topic/ET=/EUD=1/S=true

But there's no data showed in Device Statistics in /devicemgt

**Comment by madhawap** [comment]
Hi tonny,

Did you try this on IoTS-3.1.0-beta release with a real Raspberry Pi device which setup according to the schematic provided [here](https://docs.wso2.com/display/IoTS310/Raspberry+Pi#RaspberryPi-StarttheRaspberryPi)?

When you are executing testAgent.sh please enter 'No', when you are asked to run the virtual agent. Then this will work fine. Otherwise we recommend to use startService.sh script to test the sample. I tested this on IoTS-3.1.0-beta with startService.sh script and it is working fine. The graph get populated.

Please execute the startService.sh in the dowloaded Raspberry Pi agent on IoTS-3.1.0-beta in order to temperature graph to be populated on device details page.

If you encounter any difficulties please reopen this issue.

Thank you
Madhawa
