### ISSUE TITLE
Device count type is not correct in the admin dashboard 

### ISSUE THREAD

**Issue by Kamidu** [wso2/product-iots#1128]
Please refer to the screenshots. In the admin dashboard the no of device type is 3 when we go to the device type listing we can see 4 device types listed.

![image](https://user-images.githubusercontent.com/13974966/27950026-6767b5f8-631d-11e7-9b27-2f9cf8ac4a1e.png)

![image](https://user-images.githubusercontent.com/13974966/27950046-7707e3f2-631d-11e7-85ce-5d1611842cb2.png)

**Comment by dilee** [comment]
This happens if you run the IoT server without enabling the _Apple Push Notification Provider_. You can do this by simply uncommenting the following line in the **_<PRODUCT_HOME>/conf/cdm-config.xml_** file. (This step is automated in the iOS configuration script **_<PRODUCT_HOME>/ios-configurator/ios.sh_** )

`<!--<Provider>org.wso2.carbon.device.mgt.mobile.impl.ios.apns.APNSBasedPushNotificationProvider</Provider>-->`

**Comment by shavidissa** [comment]
Added this info to docs too [1].

[1] https://docs.wso2.com/display/IoTS310/Installing+iOS+Features+via+the+P2+Repository
