### ISSUE TITLE
[Windows / Location] Location is not displayed after sending the operation to an enrolled device

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1149]
OS: Windows 10
Device: Android
Pack: 3.1.0 Beta 2

Pre-Conditions:-
- Server should be configured to access via IP
- A device should be already enrolled
- Device should be synched with the IoT server

1. Login to device management UI and send location operation to an enrolled device
2. Observe the operations log
3. Observe the notification log
4. Go to location tab and check if the location is displayed

Expected Results:-
- Location operation should be successful.
- There should be no error notifications related to location
- Location tab should display the device location

Actual Results:-
- Location operation is first displayed as ERROR and if send twice its displayed as PENDING (screenshot)
- Error notification is shown related to the location (screenshot)
- Location tab displays text "Device location information is not available"

![locationtab](https://user-images.githubusercontent.com/13449310/28103925-0fc77eb4-66f6-11e7-9ba3-209202de7dc4.jpg)
![notification](https://user-images.githubusercontent.com/13449310/28103933-18475848-66f6-11e7-89fd-3a1b1eef0402.jpg)
![location](https://user-images.githubusercontent.com/13449310/28103938-1c4714ce-66f6-11e7-9c62-3ba6cfd25782.jpg)

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madhawap : Labels: Blocker, 3.1.0-beta2

**Comment by pubudup** [comment]
Observed, that the location appeared after some time (approx within 20 mins after observing the above bug.)

**Comment by madhawap** [comment]
Hi Pubudu,

If the device's location is switched off, this is reproducible and that is an expected behaviour. During the device enrollment process, it is directing you to enable location if the device location is not already enabled. But you can skip this step without enabling the location. This wouldn't affect the enrollment flow but device location data wouldn't be published although the device is completely enrolled. Please refer the screenshots attached below. 

![image](https://user-images.githubusercontent.com/12988860/28205931-c4f953be-68a1-11e7-8653-460541f365a0.png)

![image](https://user-images.githubusercontent.com/12988860/28205942-cadcd062-68a1-11e7-91c5-436dff1448b4.png)

Hence closing. Please reopen the issue if you have any further queries related to this.

**Comment by pubudup** [comment]
Verified.
