### ISSUE TITLE
[Devices] Disconnected devices are being displayed as Active

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1200]
Pre-Condition:-
- A device should be enrolled and connected to the IoTS.
- Device should be switched off (or battery should be dead)

Steps:-
1. Login to the IoTS device management page and check the device status

Expected Results:-
- Device should be displayed as inactive

Actual Results:-
- Device is displayed as active (screenshot attached)

![active1](https://user-images.githubusercontent.com/13449310/28405314-624d09d8-6d4a-11e7-863e-ed59c8305611.jpg)

![active2](https://user-images.githubusercontent.com/13449310/28405328-70663792-6d4a-11e7-90b3-ed051aeecea9.jpg)

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila : Labels: Medium, 3.1.0-RC1

**Comment by hasuniea** [comment]
This issue is not reproducible and here find the steps which I follow up
1. Enrolled both windows device and Android devices against the IoTS.
2. Hold on some time to be able to poll the server.
3. turn off the wifi on both devices.
Device state is changed into InActive in both device view and device list view.
<img width="424" alt="screen shot 2017-07-21 at 3 33 06 pm" src="https://user-images.githubusercontent.com/12996810/28459696-208a9d0c-6e2c-11e7-954d-b7cf76442a61.png">

**Comment by pubudup** [comment]
Verified that it's not reproducible in 3.1.0-RC2.
