### ISSUE TITLE
Virtual Firealarm always sends "time":0" in payload data in RC3

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1276]
Virtual Firealarm is not working as device statistics has no curve shown.
The agent log indicates  "time": 0 in payload data. Will this be the cause and how to resolve?

WSO2 IOT Sample
Virtual Fire Alarm
initializing agent

01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: jar:file:/C:/Users/citystory/Virtual%20Firealarm/wso2-firealarm-virtual-agent.jar!/deviceConfig.properties
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Tenant Domain: carbon.super
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Device Owner: admin@carbon.super
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Device ID: uboocdzonp6c
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Device Name: Virtual Firealarm
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: IoT Server HTTPS EndPoint: https://iots:8243
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: IoT Server HTTP EndPoint: http://iots:8280
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: API-Manager Gateway EndPoint: http://iots:8280
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: MQTT Broker EndPoint: tcp://iots:1886
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: XMPP Server EndPoint: XMPP:
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Base64Encoded API Application Key: dURmUnRpVDVMNUtySjJGd1V6bVl5ZEY4T3h3YTpHd01KaHNkQ1BheFkwSG1mUkd6blVLN3dzazRh
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Authentication Token: 87783dbd-b0f9-34f4-a81f-a20e83c7d0de
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Refresh Token: ab962143-9076-38cf-9421-759569edc312
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Data Push Interval: 15
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: XMPP Server Name: iots
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: IoT Server's Device Controller API Endpoint: https://iots:8243/virtual_firealarm/device
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Device Enrollment EndPoint: https://iots:8243/virtual_firealarm/device/register
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: DeviceIP Registration EndPoint: https://iots:8243/virtual_firealarm/device/register
01:11:24 [INFO] AgentUtilOperations - AGENT_LOG:: Push-Data API EndPoint: https://iots:8243/virtual_firealarm/device/temperature
01:11:24 [INFO] TransportUtils - The IP String - 'XMPP:' is invalid. It needs to be in format '<PROTOCOL>://<HOST>:<PORT>'.
01:11:24 [INFO] AgentManager - XMPP Endpoint String - XMPP:, provided in the configuration file is invalid. XMPP is not configured.
01:11:24 [INFO] MQTTTransportHandler - MQTT subscriber was created with ClientID : admin@carbon.super:uboocdzonp6c
01:11:29 [INFO] MQTTTransportHandler - Subscriber 'admin@carbon.super:uboocdzonp6c' subscribed to topic: carbon.super/virtual_firealarm/uboocdzonp6c/operation/#
01:11:45 [INFO] FireAlarmMQTTCommunicator - AGENT_LOG:: Message: '{"event": {"metaData": {"owner": "admin@carbon.super","deviceId": "uboocdzonp6c","time": 0},"payloadData": { "temperature": 22} }}' published to MQTT Queue at [tcp://iots:1886] under topic [carbon.super/virtual_firealarm/uboocdzonp6c/temperature]
01:11:47 [INFO] FireAlarmMQTTCommunicator - AGENT_LOG:: Message: '{"event": {"metaData": {"owner": "admin@carbon.super","deviceId": "uboocdzonp6c","time": 0},"payloadData": { "temperature": 21} }}' published to MQTT Queue at [tcp://iots:1886] under topic [carbon.super/virtual_firealarm/uboocdzonp6c/temperature]
01:11:49 [INFO] FireAlarmMQTTCommunicator - AGENT_LOG:: Message: '{"event": {"metaData": {"owner": "admin@carbon.super","deviceId": "uboocdzonp6c","time": 0},"payloadData": { "temperature": 49} }}' published to MQTT Queue at [tcp://iots:1886] under topic [carbon.super/virtual_firealarm/uboocdzonp6c/temperature]
01:11:51 [INFO] FireAlarmMQTTCommunicator - AGENT_LOG:: Message: '{"event": {"metaData": {"owner": "admin@carbon.super","deviceId": "uboocdzonp6c","time": 0},"payloadData": { "temperature": 34} }}' published to MQTT Queue at [tcp://iots:1886] under topic [carbon.super/virtual_firealarm/uboocdzonp6c/temperature]
01:11:53 [INFO] FireAlarmMQTTCommunicator - AGENT_LOG:: Message: '{"event": {"metaData": {"owner": "admin@carbon.super","deviceId": "uboocdzonp6c","time": 0},"payloadData": { "temperature": 29} }}' published to MQTT Queue at [tcp://iots:1886] under topic [carbon.super/virtual_firealarm/uboocdzonp6c/temperature]

![image](https://user-images.githubusercontent.com/21967994/29037297-a3540b54-7bd5-11e7-93fc-88ee8c3d0d9d.png)

**Comment by lasanthaDLPDS** [comment]
Hi citystorynet,

**Not showing real-time data**
Did you try to produce the same in the latest IoTS 3.1.0 GA pack which can be downloaded from http://wso2.com/iot. We have tested this on Linux and Windows environments.

However, as per the server logs, you have configured IoT server into a custom hostname called "iots". I believe you have also configured certificates too. At this page, the browser tries to create a **secured** WebSocket connection to the DAS server. We suspect that the browser is reject ing this connection since the certificate from DAS server is self-signed and not "localhost". 

You can easily overcome this by just accessing **http://<DAS_hostname>:<DAS_port>/carbon**(By default DAS_port is usually 9445) once and **trusting** the certificate. Then try to refresh the real-time analytics page. Please note that this step won't be required if your server certificate is CA signed, then the browser will trust the certificate. 

If the above steps don't work It would be great if you can provide us following details to analyze this further.

1. WSO2 Carbon logs which can be found on <PRODUCT_HOME>/repository/logs.
3. WSO2 Server configurations which can be found on <PRODUCT_HOME>/conf

**Sending Zero Timestamp**
The agent log that you have provided here is correct. As you explained agent send time as 0 in payload data. 

Earlier we have had issues when the device time and the server time differs. The reason to send time as 0 from the agent is temperature graph is rendered against server time. When publishing events with 0 timestamp server will add its own timestamp. Therefore, when temperature data received to the server it updates the graph with the current time of the server and temperature value. Hence, it won't be an issue for rendering virtual fire alarm statistics.

Thanks and Regards,
Lasantha

**Comment by ghost** [comment]
Hi Lasantha,
Thanks for the reply.
1. My guest VM OS is CentOS7
2. Server running on guest VM (iots) and agent running on host (Win 10 Pro)

I have resolved this on the release version of 3.1.0.
But I am not sure if this is due to moving the server to real VPS and
connect from my PC (Win 10 Pro)
The other change I have made is that instead of manually configure hostname
for the server.
This time I have used the new change-ip.sh.
Thanks anyways. Please close it.

Clement

**Comment by ruwany** [comment]
Hi @citystorynet ,

This issue is fixed in the latest update of wso2 IoT server that went out yesterday.

https://github.com/wso2/product-iots/releases/tag/v3.1.0-update1

Thanks,
Ruwan
