### ISSUE TITLE
[Android] Work profile is not removing upon agent unregistration.

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-iots#1332]
If the agent in the work-profile is uninstalled, the work-profile has to be deleted from the device.

**Comment by dilee** [comment]
**Steps followed to reproduce:**
1. Enroll a device with a work profile.
2. Try to uninstall the agent in the profile.

**Expected Behaviour:**
1. The agent in the profile should get uninstalled.
2. The profile should get deleted along with the data.

**Actual Behaviour:** 
1. The agent in the device gets uninstalled when trying to uninstall the agent in the profile
2. When trying to uninstall the agent in the profile again, it requests to delete the profile hence adhering to the expected behavior.

**Comment by charithag** [comment]
Ideally the scenario should be as follows:

**Steps followed to reproduce:**

1. Enroll a device with a work profile.
2. Try to unregister the agent in the profile.

**Expected Behavior:**

1. After unregistering the agent, work profile should get deleted along with the data.

**Comment by charithag** [comment]
Fixed with PR https://github.com/wso2/cdmf-agent-android/pull/77
