### ISSUE TITLE
WSO2 IOT 3.1.0 all versions : strange warm 

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1361]
Hi,
When I look at the logs, I find 4 warms which I would like to have explanations.

I specify that it's warm are for any new installation of WSO2 IOT 3.1.0 all versions

```
No artifacts found to be deployed in this server. Ignoring Carbon Application : org_wso2_carbon_iot_geo_dashboard-1.0.0.car 

windows-default-platform-configuration.xml is not available, hence default windowsplatform configuration cannot be loaded. 	

android_sense-default-platform-configuration.xml is not available, hence default android_senseplatform configuration cannot be loaded. 	

android-default-platform-configuration.xml is not available, hence default androidplatform configuration cannot be loaded. 
```
Subsequently, after installing the samples, I also have this which is present from now on :

```
Attempt to reinitialize APIStatusObserverList - Skipping 	

virtual_firealarm-default-platform-configuration.xml is not available, hence default virtual_firealarmplatform configuration cannot be loaded. 	

raspberrypi-default-platform-configuration.xml is not available, hence default raspberrypiplatform configuration cannot be loaded. 	

arduino-default-platform-configuration.xml is not available, hence default arduinoplatform configuration cannot be loaded. 
```	

Many Thanks for your reply.

**Comment by madawas** [comment]
@Tofdu31 Please find my explanation below.
```
No artifacts found to be deployed in this server. Ignoring Carbon Application : org_wso2_carbon_iot_geo_dashboard-1.0.0.car 
```
This WARN log appears when the server role of the carbon app and the server profile does not match. In this case, this log appears because the analytics related carbon app is going to be deployed in the IOT core server which is unnecessary. So you can ignore the log for now.

```
<device_type>-default-platform-configuration.xml is not available, hence default windows platform configuration cannot be loaded.
```
There is a feature that you can add a default platform configuration specific for a device type so that the platform configurations are automatically set for all the tenants. This WARN appears when such default platform configuration is not available for a device type. This is an INFO type log but printed as WARN to get attention when debugging. So you can ignore this log as it doesn't do any harm.

```
Attempt to reinitialize APIStatusObserverList - Skipping
```
This log prints from this [line](https://github.com/wso2/carbon-appmgt/blob/a40df2bb2f5ccf7cec6e039251c5ef5b368d7d03/components/org.wso2.carbon.appmgt.impl/src/main/java/org/wso2/carbon/appmgt/impl/observers/APIStatusObserverList.java#L48) and you can clearly see that the log gets printed when the `APIStatusObserverList` is already initialized. Ideally, this should be a debug type log and we will fix it. For the time being, you can ignore this WARN as well.

**Comment by ghost** [comment]
@madawas many thanks for your reply
Thank you for taking the time to answer me and bring me this information
