### ISSUE TITLE
Pushing policies to android results in Invalid DeviceIdentifiers found

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1440]
**Description:**
I believe this is happening because the IoT server is trying to push the policies to removed phones but I am not 100% sure. Sometimes the policies still get pushed but I've seen cases with application white lists enabled where nothing happened but that might be another issue all together.

Attached logs:
[Identifier error.txt](https://github.com/wso2/product-iots/files/1362171/Identifier.error.txt)

**Suggested Labels:**
Policy, Android, Error

**Affected Product Version:**
IoT 3.1.0

**OS, DB, other environment details and versions:**    
Linux OS & Postgresql database

**Steps to reproduce:**
In policy management change a policy
Apply changes to devices 
Check logs for errors

**Comment by ghost** [comment]
Started happening in IoT3.1.0 update 4 again now too.. Policies are not functioning anymore after a while.

**Comment by ruwany** [comment]
If you are seeing errors like E.g. :

[IoT-Core] ERROR - {org.wso2.carbon.mdm.services.android.services.impl.DeviceManagementServiceImpl} Device not found for identifier '25b8dec42de5715b'

This could be due to the fact that, a device that has been marked as "Removed" from the devicemgt console, maybe trying to sync with the IoT Server. Removing a device from the console does not trigger an uninstall of the agent running on the device, however, if the agent were to be removed from the device, the server will get notified and the respective device will get updated as removed in the carbon console. 

I do not believe this error is related to the whitelisting issue that you have indicated. We have shipped the latest update release of IoT Server last Thursday [(here)](https://github.com/wso2/product-iots/releases/download/v3.1.0-update10/wso2iot-3.1.0-update10.zip), with the latest agent. This new agent carries all the fixes we have done with regards to app-whitelisting and other areas. 

Appreciate if you could test our your flow with the newest release and let us know if you encounter any issues.

I am going to mark this issue as closed, hence the answer has been provided above.
