### ISSUE TITLE
Unable to sign in to Carbon Management console

### ISSUE THREAD

**Issue by nemanjanedic** [wso2/product-iots#1462]
**Description:**
After fresh start of the IOT server, I am not able to log into the Carbon Management console. When logging in, I get `Error 403 - Forbidden`. In the logs I see this:
```
[2017-11-07 18:16:02,108] [IoT-Core]  WARN - {org.owasp.csrfguard.log.JavaLogger} potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:127.0.0.1, method:POST, uri:/carbon/admin/login_action.jsp, error:required token is missing from the request)
```
I've tried this in both Chrome and Firefox.

**Suggested Labels:**

Type/Bug, 3.1.0-Update5, High

**Suggested Assignees:**

**Affected Product Version:**
WSO2 IoT Server 3.1.0 UPDATE 5

**OS, DB, other environment details and versions:**    
Mac OS X 10.13.1

**Steps to reproduce:**
1. Download zip from GitHub (https://github.com/wso2/product-iots/releases)
1. Unzip it
1. Run `bin/broker.sh`
1. Run `bin/iot-server.sh`
1. Run `bin/analytics.sh`
1. Open `https://localhost:9443/carbon/admin/login.jsp`
1. Sign is as admin/admin

**Related Issues:**

**Comment by ruwany** [comment]
You may have faced this error due to the server not starting up correctly. Can you attach the full server log here, for verification? 
I am marking this issue as closed. However, if you encounter this issue again. Do not hesitate to re-open.

**Comment by rasika** [comment]
Hi nemanjanedic,

We are sincerely apologize for the issue that you are getting. Root cause for the issue is due to the JDK version you are using. Please make sure that you are using JDK 1.8_144 or any other recommended JDK version. We have also added this into our [doc space](https://docs.wso2.com/display/IoTS310/WSO2+IoT+Server+Documentation);

`Due to a [known issue](https://bugs.openjdk.java.net/browse/JDK-8189789) do not use JDK1.8.0_151 with WSO2 products. Use JDK 1.8.0_144 until JDK 1.8.0_162-ea is released.`

If downgrading JDK is not working, try disabling GZip compression from the tomcat server as a temporary fix. You can access the **catalina-server.xml** inside the **$IOT_HOME/conf/tomcat**. Open up it in a text editor and replace the following parameter into "compression=off" for the both <Connector> elements.

<Connector protocol="org.apache.coyote.http11.Http11NioProtocol"
                   ..//other attributes
                   compression="off">

**Comment by mmaker1234** [comment]
Hello,
It seems the problem is **not** resolved with JDK 1.8.0_162. I am using JDK 1.8.0_162-b12 and have the same problem with log-in to Carbon for WSO2 API-M. Thanks the workaround (compression disable) still works.

**Comment by rasika** [comment]
Hi, we just released WSO2 IoT Server 3.2.0 with the above fix. Product pack can be downloaded via https://wso2.com/iot page.

**Comment by chicho1991** [comment]
mmaker can you please tell me whats "compression disable" is and how you do it.
i am facing the same issue with logging in to WSO2 Carbon website
thank you in advance

**Comment by rasika** [comment]
@chicho1991 Please refer my comment on "Dec 11, 2017" in this ticket. It has instructions to disable the compression.
