### ISSUE TITLE
Problem with remote control feature  WSO2IOT3.1.0.0-Update8 

### ISSUE THREAD

**Issue by Nfoudikue** [wso2/product-iots#1548]
Remote fearture in device management still on "Waiting on device to connect" and nothing is displayed on remote phone.
![image](https://user-images.githubusercontent.com/24441895/34171942-888edbda-e4f0-11e7-9804-1c600576039e.png)

The device is active.
![image](https://user-images.githubusercontent.com/24441895/34172346-02bcaa6c-e4f2-11e7-8f71-f2cec2b421d5.png)

I have changed RemoteSessionServerUrl in IOTHOME/conf/cdm-config.xml even in wso2/analytics/conf and broker/conf  by IP nothing is happen.

 
    <RemoteSessionConfiguration>
        <Enabled>true</Enabled>
        <RemoteSessionServerUrl>wss://localhost:9443</RemoteSessionServerUrl>
        <MaximumHTTPConnectionPerHost>2</MaximumHTTPConnectionPerHost>
        <MaximumTotalHTTPConnections>100</MaximumTotalHTTPConnections>
        <MaximumMessagesPerSecond>20</MaximumMessagesPerSecond>
        <SessionIdleTimeOut>15</SessionIdleTimeOut>
        <MaximumMessageBufferSize>640</MaximumMessageBufferSize>
    </RemoteSessionConfiguration>
    <DefaultGroupsConfiguration>BYOD,COPE</DefaultGroupsConfiguration>
</DeviceMgtConfiguration>

OS: Centos 6.7 and 7.4

Regards

**Comment by charithag** [comment]
Hi, In order to work with remote control feature it is needed to enroll your device as a COPE device along with System Service. Please refer documentation on [Integrating the Android System Service Application](https://docs.wso2.com/display/IoTS310/Integrating+the+Android+System+Service+Application) for more details about integrating system service. I have already created an [issue](https://github.com/wso2/product-iots/issues/1564) to remove Remote Control operation from none COPE devices.
