### ISSUE TITLE
Cannot black-list a single android app

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#365]
When we try to black-list single android app, response code is 500. But it works fine when we try to black-list 2 android-apps.

**Comment by madhawap** [comment]
This issue is no longer reproducible in 3.1.0-alpha. We can successfully blacklist a single android app.  

Blacklisting policy is built around the "getRunningAppProcesses()" function in the Android ActivityManager API. However, as of Android 5.1.1, this API has been deprecated. Therefore, we are unable to support this functionality for BYOD devices running Android version 5.1.1 or higher.
