### ISSUE TITLE
cannot access the WSO2 DAS Console

### ISSUE THREAD

**Issue by yanyuxiyangzk** [wso2/product-iots#418]
##When i access DAS Console,.i input this address https://<IoTS_HOST>:9445/portal, <IoTS_HOST> is   my  host ip.Then  some thins happened which redireact to https://localhost:9443/samlsso.  I do not knwon what is wrong with my iot.

Iot version is 3.0.0

**Comment by Megala21** [comment]
Since IOT 3.0.0 is configured to have SSO by default, for the quick start-up, we have configured the SSO parameters to work with 'localhost', To make it work with the ip address, we need to make the configurations mentioned in [1]. In this we have missed to include the details on configuring "/portal". I have created an issue to track this[2]. To make this portal to work with ip, please configure the following attributes in
`{IOT_HOME}/analytics/repository/deployment/server/jaggeryapps/portal/configs/designer.json`
```
 "identityProviderURL": "https://<IoTS_HOST>:9443/samlsso",
 "acs": "https://<IoTS_HOST>:9445/portal/acs",
```
under authentication/methods/sso/attributes (Here IoTs_HOST is your ip address). This should solve the above issue. In addition to that when configuring the ip address, in order to access the portal without issues, we need to add the certificate for that ip address, please refer [3] for configuring certificate for that ip address. Please note that in [3], it mentions about a configuration file named "portal.json", in IOT 3.0.0, it is the same 'designer.json' which is mentioned above.

[1] https://docs.wso2.com/display/IoTS300/Configuring+WSO2+IoT+Server+with+the+IP
[2] https://github.com/wso2/product-iots/issues/438
[3] https://docs.wso2.com/display/DS200/Troubleshooting+Guide

Thanks.

**Comment by Megala21** [comment]
#438

**Comment by yanyuxiyangzk** [comment]
It is a bug in old version
