### ISSUE TITLE
WSO2 iOT :  Failed clean up Carbon core

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#474]
[Log Wso2IoT - Broker.txt](https://github.com/wso2/product-iots/files/1012635/Log.Wso2IoT.-.Broker.txt)

hi all,

I study WSO2 IOT for several months. I get WSO2 iOT on Jenkins to see the evolutions.

I managed to parameterize it with my IP. Next to this request is the log file.

I look but I can not find the error.

Thank you for your help

Christophe

But the broker is not ok...

**Comment by Megala21** [comment]
Hi,

With the logs, it seems like it could not bind to the port "5675", as per the following line in the provided logs,
`Caused by: org.wso2.andes.transport.TransportException: Could not bind to /163.172.90.197:5675`

Can you check whether any other processes are using this port? This was the reason, it could not start-up the broker.

**Comment by ghost** [comment]
On the debian, with the command `netstat -ltunp` 
We realize that I have this line, which I do not understand

`tcp        0      0 0.0.0.0:5675            0.0.0.0:*               LISTEN      8811/java`

Apparently, it's java. Do you have a solution to bypass this problem?

Thank

**Comment by ghost** [comment]
Sorry, I had a problem with my server. I'm closing.
Thanks for helping me.
