### ISSUE TITLE
[EMM-1893] Unable to install apps from unknown sources in android work profile

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#530]
Tried to push an enterprise android app onto the user device but it prompts "Your administrator doesn't allow installation of apps obtained from unknown sources." even though the device has allowed app installation from unknown sources. The device policy in the android configuration in the emm console has also been set to allow installation from unknown sources.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1893'>https://wso2.org/jira/browse/EMM-1893</a></p>

**Comment by pasindujw** [comment]
Hi,
By default, Unknown sources are automatically blocked in the Work Profile due to security purpose by Android itself. In addition to that EMMs are also encouraged not to surface policy controls to change such default states as well. Therefore in order to adhere with the EMM requirements [1] given by Android for EMM vendors, we have to stick with it.

[1] [https://developers.google.com/android/work/requirements/work-profile](url)
(Please refer 2.7 Default security policies.)

Thanks.

**Comment by inoshperera** [comment]
Resolving based on the comment.
