### ISSUE TITLE
[IOTS-485] Install app catalog application non-existant

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#623]
The 3.0 documentation says to go to https://&lt;IoT_HOST&gt;:9443/store from the mobile device. That page shows the store site but doesn't offer the user to download any catalog apk. The users must first install the app catalog application on the device from the App store: https://&lt;IoT_HOST&gt;:9443/store/ - this "app catalog application" doesn't exist. Not sure how this is supposed to work.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-485'>https://wso2.org/jira/browse/IOTS-485</a></p>

**Comment by Megala21** [comment]
@shavidissa - Seems like the issue is regarding the doc at [1]. May be we can provide an information/link on how to install the app catalog application to our app store.

[1] https://docs.wso2.com/display/IoTS300/App+Catalog+Application+for+Android+Devices

**Comment by SuperMasterBlasterLaser** [comment]
In documenation of last version of IoTS there are no [mentions about App catalog](https://docs.wso2.com/display/IoTS310/Working+with+Android+Devices)

**Comment by ghost** [comment]
Would like to know if the app-catalog has been discontinued or not.

**Comment by shavidissa** [comment]
Thank you, Megala! I updated the 3.0.0 docs by asking users to first publish the application to the store.

[1] https://docs.wso2.com/display/IoTS300/App+Catalog+Application+for+Android+Devices

There are some known issues in the app catalog application in 3.1.x versions of IoT server and we will be fixing them in the future releases.

I am closing this Issue because it is a documentation gap. Issue [2] will be closed when things are fixed.

[2] https://github.com/wso2/product-iots/issues/419
