### ISSUE TITLE
[IOTS-209] Devices: The user is able to duplicate the device name

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#652]
Steps:  1.Devices should be deployed 2.An aleready downloaded device should exist 3.The device user should be logged in 4. click on the device and enter a device name that already exist Actual result: The user is able to create a device with the same name. Refer image Expected result: the device should not be downloaded to the users computer.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-209'>https://wso2.org/jira/browse/IOTS-209</a></p>

**Comment by geethkokila** [comment]
Name of the device is not a unique identifier in the IoT server, therefore we do not enforce any rules for having the same name for the device. If we enforce that rule, Device enrollment will fail because, in case of Android, device name will be same for model such as Galaxy 8 and Nexus 5x (bullhead).
