### ISSUE TITLE
[IOTS-312] Add geo fencing capabilities

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#768]
<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-312'>https://wso2.org/jira/browse/IOTS-312</a></p>

**Comment by rasika** [comment]
Fixed with following PRs
https://github.com/wso2/carbon-device-mgt/pull/755
https://github.com/wso2/carbon-device-mgt/pull/806
https://github.com/wso2/carbon-device-mgt-plugins/pull/687
https://github.com/wso2/carbon-device-mgt-plugins/pull/718
https://github.com/wso2/product-iots/pull/708
https://github.com/wso2/product-iots/pull/1020
